spring.application.name=taskmanager

# PostgreSQL - Supabase
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:6543/postgres?user=postgres.uedzbsaqagqugmanlbhg&password=Satyajeet@2026&sslmode=require&prepareThreshold=0
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Connection Pool - tuned for Supabase Transaction Pooler
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.keepalive-time=60000
spring.datasource.hikari.auto-commit=true

# Disable prepared statements - required for Supabase Transaction Pooler
spring.jpa.properties.hibernate.jdbc.use_get_generated_keys=true
spring.jpa.properties.hibernate.connection.provider_disables_autocommit=false
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# JWT
jwt.secret=satyajeet_taskmanager_super_secret_key_256bit_long_enough_for_hs256
jwt.expiration=86400000

# Server
server.port=8080