spring.application.name=taskmanager

# PostgreSQL - Supabase
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:6543/postgres?user=postgres.uedzbsaqagqugmanlbhg&password=Satyajeet@2026&sslmode=require
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Fix transaction issues
spring.datasource.hikari.auto-commit=true
spring.jpa.properties.hibernate.connection.provider_disables_autocommit=false

# JWT
jwt.secret=satyajeet_taskmanager_super_secret_key_256bit_long_enough_for_hs256
jwt.expiration=86400000

# Server
server.port=8080